"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

class crazyflie_thrust_t(object):
    __slots__ = ["timestamp", "thrust1", "thrust2", "thrust3", "thrust4"]

    def __init__(self):
        self.timestamp = 0
        self.thrust1 = 0
        self.thrust2 = 0
        self.thrust3 = 0
        self.thrust4 = 0

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(crazyflie_thrust_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qhhhh", self.timestamp, self.thrust1, self.thrust2, self.thrust3, self.thrust4))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != crazyflie_thrust_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return crazyflie_thrust_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = crazyflie_thrust_t()
        self.timestamp, self.thrust1, self.thrust2, self.thrust3, self.thrust4 = struct.unpack(">qhhhh", buf.read(16))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if crazyflie_thrust_t in parents: return 0
        tmphash = (0x35fe4804d0b69f6d) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if crazyflie_thrust_t._packed_fingerprint is None:
            crazyflie_thrust_t._packed_fingerprint = struct.pack(">Q", crazyflie_thrust_t._get_hash_recursive([]))
        return crazyflie_thrust_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

