"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class crazyflie_controller_commands_t(object):
    __slots__ = ["is_running"]

    def __init__(self):
        self.is_running = False

    def encode(self):
        buf = BytesIO()
        buf.write(crazyflie_controller_commands_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">b", self.is_running))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != crazyflie_controller_commands_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return crazyflie_controller_commands_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = crazyflie_controller_commands_t()
        self.is_running = bool(struct.unpack('b', buf.read(1))[0])
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if crazyflie_controller_commands_t in parents: return 0
        tmphash = (0x8fb1c6d69e1bf68c) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if crazyflie_controller_commands_t._packed_fingerprint is None:
            crazyflie_controller_commands_t._packed_fingerprint = struct.pack(">Q", crazyflie_controller_commands_t._get_hash_recursive([]))
        return crazyflie_controller_commands_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

