"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

class crazyflie_state_estimate_t(object):
    __slots__ = ["timestamp", "xhat"]

    def __init__(self):
        self.timestamp = 0
        self.xhat = [ 0.0 for dim0 in range(12) ]

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(crazyflie_state_estimate_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestamp))
        buf.write(struct.pack('>12d', *self.xhat[:12]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != crazyflie_state_estimate_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return crazyflie_state_estimate_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = crazyflie_state_estimate_t()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        self.xhat = struct.unpack('>12d', buf.read(96))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if crazyflie_state_estimate_t in parents: return 0
        tmphash = (0x4ab2098a76431c55) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if crazyflie_state_estimate_t._packed_fingerprint is None:
            crazyflie_state_estimate_t._packed_fingerprint = struct.pack(">Q", crazyflie_state_estimate_t._get_hash_recursive([]))
        return crazyflie_state_estimate_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

