"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class vortex_sensor_t(object):
    __slots__ = ["sensor1", "sensor2", "velocity"]

    def __init__(self):
        self.sensor1 = 0.0
        self.sensor2 = 0.0
        self.velocity = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(vortex_sensor_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">ddd", self.sensor1, self.sensor2, self.velocity))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != vortex_sensor_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return vortex_sensor_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = vortex_sensor_t()
        self.sensor1, self.sensor2, self.velocity = struct.unpack(">ddd", buf.read(24))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if vortex_sensor_t in parents: return 0
        tmphash = (0x3525d46ae32101c3) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if vortex_sensor_t._packed_fingerprint is None:
            vortex_sensor_t._packed_fingerprint = struct.pack(">Q", vortex_sensor_t._get_hash_recursive([]))
        return vortex_sensor_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

